Repository ironcore-dev/cloud-hypervisor-provider, pull requests merged in 2025-07, with the labels that each got.

#71 Improved `VM` process handling
  api/machine.go
  cmd/cloud-hypervisor-provider/app/app.go
  go.mod
  go.sum
  internal/controllers/machine_controller.go
  internal/host/paths.go
  internal/plugins/volume/ceph/ceph.go
  internal/plugins/volume/ceph/qemu-storage.go
  internal/plugins/volume/ceph/qmp.go
  internal/plugins/volume/ceph/socket.go
  internal/plugins/volume/emptydisk/emptydisk.go
  internal/plugins/volume/plugins.go
  internal/server/machine.go
  internal/server/machine_volume_detach.go
  internal/server/machine_volume_detach_test.go
  internal/server/server_suite_test.go
  internal/vmm/manager.go
  internal/vmm/socket.go
Labels: enhancement, size/XXL, area/compute, area/iaas

#72 Improved image build
  Dockerfile
  config/manager/manager.yaml
Labels: enhancement, size/S, area/compute, area/iaas

#80 Bump `k8s.io/*` deps to v1.33.3
  go.mod
  go.sum
Labels: size/M, area/compute, area/iaas

#87 Build edk2 firmware for cloud hypervisor
  .github/workflows/edk2.yml
Labels: size/M
